import type { Product } from "@/types";

export const SEED_PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "coquette-romance-jar",
    name: "Coquette Romance Jar",
    category: "Aesthetic",
    shortDescription: "Soft, romantic, feminine — pearls, bows, rose gold accents.",
    description:
      "A soft-glam jar filled with pearl-like accents, bows, delicate chains, and romantic details. Made for outfits that feel feminine, polished, and photo-ready. Every piece inside is chosen to complement soft, feminine aesthetics — from delicate lace-inspired details to dreamy rose-gold finishes.",
    price: 599,
    compareAtPrice: 799,
    pieceCountMin: 5,
    pieceCountMax: 10,
    moodTags: ["Romantic", "Feminine", "Soft Glam", "Gifting"],
    colourPalette: ["Pearl", "Blush", "Rose Gold", "Cream"],
    metalTones: ["Rose Gold", "Gold"],
    includedTypes: ["Necklace / Pendant", "Earrings", "Rings", "Stack Bracelets"],
    images: [],
    emoji: "🌸",
    accentColor: "#f7c5cc",
    stock: 8,
    lowStockThreshold: 3,
    isLimitedDrop: true,
    dropEndsAt: "2026-06-30T23:59:59Z",
    isCustomizable: true,
    featuredRank: 1,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "2",
    slug: "grunge-fairy-core-jar",
    name: "Grunge Fairy Core Jar",
    category: "Aesthetic",
    shortDescription: "Moody, whimsical, earthy — antique silver, crystals, nature charms.",
    description:
      "A moody yet whimsical jar built for expressive souls. Expect antique silver tones, raw crystal-style pieces, mushroom charms, star accents, and nature-inspired details. Perfect for creative outfits and layered, eclectic looks.",
    price: 599,
    compareAtPrice: 799,
    pieceCountMin: 5,
    pieceCountMax: 10,
    moodTags: ["Moody", "Whimsical", "Earthy", "Expressive"],
    colourPalette: ["Smoke", "Forest", "Antique Silver", "Plum"],
    metalTones: ["Silver", "Gunmetal"],
    includedTypes: ["Necklace / Pendant", "Rings", "Earrings", "Armlet"],
    images: [],
    emoji: "🍄",
    accentColor: "#6b5e4e",
    stock: 5,
    lowStockThreshold: 2,
    isLimitedDrop: false,
    isCustomizable: true,
    featuredRank: 2,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "3",
    slug: "clean-girl-minimalist-jar",
    name: "Clean Girl Minimalist Jar",
    category: "Aesthetic",
    shortDescription: "Polished, everyday luxury — gold chains, huggies, geometric rings.",
    description:
      "A refined everyday jar for those who wear less but wear it better. Thin gold chains, huggies, geometric rings, delicate bracelets, and minimal pendants. Perfect for daily layering, college, and office looks.",
    price: 499,
    compareAtPrice: 699,
    pieceCountMin: 5,
    pieceCountMax: 10,
    moodTags: ["Minimalist", "Everyday", "Office", "Layering"],
    colourPalette: ["Champagne", "Gold", "Ivory", "Nude"],
    metalTones: ["Gold"],
    includedTypes: ["Necklace / Pendant", "Rings", "Earrings", "Stack Bracelets"],
    images: [],
    emoji: "✨",
    accentColor: "#e8c97a",
    stock: 12,
    lowStockThreshold: 4,
    isLimitedDrop: false,
    isCustomizable: true,
    featuredRank: 3,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "4",
    slug: "streetwear-chunky-jar",
    name: "Streetwear Chunky Jar",
    category: "Aesthetic",
    shortDescription: "Bold, edgy, statement — curb chains, oversized rings, chrome accents.",
    description:
      "Made for the bold. Curb chains, oversized rings, chunky pendants, steel-look pieces, and bold earrings. This jar is built for reels, parties, and streetwear fits that demand attention.",
    price: 649,
    compareAtPrice: 849,
    pieceCountMin: 5,
    pieceCountMax: 10,
    moodTags: ["Bold", "Edgy", "Statement", "Party"],
    colourPalette: ["Silver", "Black", "Chrome", "Red Accent"],
    metalTones: ["Silver", "Gunmetal"],
    includedTypes: ["Necklace / Pendant", "Rings", "Earrings", "Stack Bracelets"],
    images: [],
    emoji: "⛓️",
    accentColor: "#5a5a5a",
    stock: 7,
    lowStockThreshold: 3,
    isLimitedDrop: true,
    isCustomizable: true,
    featuredRank: 4,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "5",
    slug: "that-90s-vibe-jar",
    name: "That '90s Vibe Jar",
    category: "Pop Culture",
    shortDescription: "Playful, nostalgic, colourful — beaded chokers, daisy motifs, smiley accents.",
    description:
      "Take it back to the nineties. Beaded chokers, seed bead rings, daisy motifs, smiley accents, and colourful acrylic pieces. A playful jar perfect for gifting and casual, fun styling.",
    price: 449,
    compareAtPrice: 599,
    pieceCountMin: 5,
    pieceCountMax: 10,
    moodTags: ["Nostalgic", "Playful", "Colourful", "Gifting"],
    colourPalette: ["Candy Pink", "Daisy Yellow", "Aqua", "Pastel Green"],
    metalTones: ["Gold", "Silver", "Mixed"],
    includedTypes: ["Necklace / Pendant", "Earrings", "Rings", "Anklets"],
    images: [],
    emoji: "🌼",
    accentColor: "#ff90b3",
    stock: 15,
    lowStockThreshold: 5,
    isLimitedDrop: false,
    isCustomizable: true,
    featuredRank: 5,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "6",
    slug: "midnight-gothic-jar",
    name: "Midnight Gothic Jar",
    category: "Pop Culture",
    shortDescription: "Dark, dramatic, mysterious — all-black jewellery, gunmetal chains, snake charms.",
    description:
      "A darker SERENA jar built with black, gunmetal, and dramatic jewellery accents. All-black jewellery, gunmetal chains, obsidian-style accents, snake charms, and chokers. Designed for bold styling, night looks, and statement energy.",
    price: 649,
    compareAtPrice: 899,
    pieceCountMin: 5,
    pieceCountMax: 10,
    moodTags: ["Dark", "Dramatic", "Gothic", "Night Looks"],
    colourPalette: ["Black", "Gunmetal", "Deep Red", "Charcoal"],
    metalTones: ["Gunmetal", "Silver"],
    includedTypes: ["Necklace / Pendant", "Rings", "Earrings", "Armlet"],
    images: [],
    emoji: "🖤",
    accentColor: "#1a1a2e",
    stock: 4,
    lowStockThreshold: 2,
    isLimitedDrop: true,
    dropEndsAt: "2026-07-15T23:59:59Z",
    isCustomizable: true,
    featuredRank: 6,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "7",
    slug: "sun-stars-celestial-jar",
    name: "Sun & Stars Celestial Jar",
    category: "Pop Culture",
    shortDescription: "Dreamy, cosmic, magical — moon charms, zodiac signs, iridescent pieces.",
    description:
      "A dreamy jar for cosmic souls. Moon charms, sunbursts, zodiac sign accents, stars, tarot-inspired pendants, and iridescent pieces. Perfect for birthdays, zodiac gifting, and dreamy aesthetic dressing.",
    price: 599,
    compareAtPrice: 799,
    pieceCountMin: 5,
    pieceCountMax: 10,
    moodTags: ["Dreamy", "Cosmic", "Birthday", "Zodiac"],
    colourPalette: ["Gold", "Midnight Blue", "Pearl", "Iridescent"],
    metalTones: ["Gold", "Silver", "Mixed"],
    includedTypes: ["Necklace / Pendant", "Earrings", "Rings", "Stack Bracelets"],
    images: [],
    emoji: "🌙",
    accentColor: "#312e81",
    stock: 9,
    lowStockThreshold: 3,
    isLimitedDrop: false,
    isCustomizable: true,
    featuredRank: 7,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "8",
    slug: "ocean-breeze-tropical-jar",
    name: "Ocean Breeze Tropical Jar",
    category: "Pop Culture",
    shortDescription: "Beachy, fresh, vacation-ready — turquoise stones, shells, sea-glass beads.",
    description:
      "Carry the ocean with you. Turquoise-style stones, sea-glass beads, shell charms, anklets, and breezy summer earrings. Built for vacations, beach outfits, and summer styling.",
    price: 549,
    compareAtPrice: 749,
    pieceCountMin: 5,
    pieceCountMax: 10,
    moodTags: ["Beachy", "Summer", "Vacation", "Fresh"],
    colourPalette: ["Turquoise", "Sand", "Shell White", "Sea Green"],
    metalTones: ["Gold", "Silver"],
    includedTypes: ["Necklace / Pendant", "Earrings", "Anklets", "Stack Bracelets"],
    images: [],
    emoji: "🌊",
    accentColor: "#0e7490",
    stock: 11,
    lowStockThreshold: 4,
    isLimitedDrop: false,
    isCustomizable: true,
    featuredRank: 8,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "9",
    slug: "statement-jar",
    name: "Statement Jar",
    category: "Tiered",
    shortDescription: "At least one head-turning piece — statement earrings, chunky necklace, dramatic ring.",
    description:
      "Guaranteed to include at least one bold, head-turning piece. Statement earrings, a chunky layered necklace, a dramatic ring, and matching accent pieces. Built for parties, photoshoots, and events where you need to own the room.",
    price: 799,
    compareAtPrice: 999,
    pieceCountMin: 5,
    pieceCountMax: 10,
    moodTags: ["Party", "Shoot", "Events", "Statement"],
    colourPalette: ["Gold", "Pearl", "Black", "Mixed"],
    metalTones: ["Gold", "Silver", "Gunmetal", "Mixed"],
    includedTypes: ["Necklace / Pendant", "Earrings", "Rings", "Armlet"],
    images: [],
    emoji: "💎",
    accentColor: "#c6a15b",
    stock: 6,
    lowStockThreshold: 2,
    isLimitedDrop: true,
    isCustomizable: true,
    featuredRank: 9,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "10",
    slug: "daily-stack-jar",
    name: "Daily Stack Jar",
    category: "Tiered",
    shortDescription: "Layerable everyday pieces — rings, bracelets, thin necklaces, huggies.",
    description:
      "A wearable layering jar for everyday styling. Expect delicate rings, bracelets, huggies, and subtle pieces that work together without effort. Build your daily stack without thinking twice.",
    price: 449,
    compareAtPrice: 599,
    pieceCountMin: 5,
    pieceCountMax: 10,
    moodTags: ["Daily Wear", "Minimal", "Layering", "Office"],
    colourPalette: ["Gold", "Ivory", "Champagne", "Pearl"],
    metalTones: ["Gold", "Rose Gold"],
    includedTypes: ["Rings", "Stack Bracelets", "Necklace / Pendant", "Earrings"],
    images: [],
    emoji: "🔗",
    accentColor: "#ead8b7",
    stock: 18,
    lowStockThreshold: 5,
    isLimitedDrop: false,
    isCustomizable: true,
    featuredRank: 10,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "11",
    slug: "lucky-dip-jar",
    name: "Lucky Dip Jar",
    category: "Tiered",
    shortDescription: "Budget-friendly surprise — charms, rings, studs, mini statement pieces.",
    description:
      "The perfect impulse buy and starter jar. Curated with smaller accessories, charms, rings, studs, and mini statement pieces. A delightful surprise every time — and perfect for gifting when you want something personal without the full budget.",
    price: 399,
    compareAtPrice: 549,
    pieceCountMin: 5,
    pieceCountMax: 10,
    moodTags: ["Gifting", "Surprise", "Budget", "Fun"],
    colourPalette: ["Mixed", "Pastel", "Gold", "Silver"],
    metalTones: ["Mixed"],
    includedTypes: ["Rings", "Earrings", "Necklace / Pendant", "Anklets"],
    images: [],
    emoji: "🎁",
    accentColor: "#d9a0a8",
    stock: 20,
    lowStockThreshold: 6,
    isLimitedDrop: false,
    isCustomizable: false,
    featuredRank: 11,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return SEED_PRODUCTS.find((p) => p.slug === slug);
}

export function getFeaturedProducts(count = 8): Product[] {
  return [...SEED_PRODUCTS]
    .sort((a, b) => (a.featuredRank ?? 99) - (b.featuredRank ?? 99))
    .slice(0, count);
}

export function getRelatedProducts(product: Product, count = 3): Product[] {
  return SEED_PRODUCTS.filter(
    (p) =>
      p.id !== product.id &&
      (p.category === product.category ||
        p.moodTags.some((t) => product.moodTags.includes(t)))
  ).slice(0, count);
}
